// Code generated by goctl. DO NOT EDIT.
package types

type SignInRequest struct {
	Code  string `form:"code"`
	State string `form:"state"`
}

type SignInResponse struct {
	Status string `json:"status"`
}

type UserInfoResponse struct {
	Status string   `json:"status"`
	Data   UserInfo `json:"data"`
}

type UserInfo struct {
	DisplayName string `json:"displayNname"`
	Avatar      string `json:"avatar"`
}

type RefreshResponse struct {
	Status string `json:"status"`
}
