// Code generated by goctl. DO NOT EDIT.
package types

type SignInRequest struct {
	Code  string `form:"code"`
	State string `form:"state"`
}

type SignInResponse struct {
	Status string    `json:"status"`
	Data   TokenPair `json:"data"`
}

type TokenPair struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type UserInfoRequest struct {
	AccessToken string `header:"Authorization"`
}

type UserInfoResponse struct {
	Status string   `json:"status"`
	Data   UserInfo `json:"data"`
}

type UserInfo struct {
	DisplayName string `json:"displayNname"`
	Avatar      string `json:"avatar"`
}

type SetCookieRequest struct {
	RefreshToken string `header:"Authorization"`
}

type SetCookieResponse struct {
	Status      string `json:"status"`
	AccessToken string `json:"data"`
}

type RefreshResponse struct {
	Status      string `json:"status"`
	AccessToken string `json:"data"`
}
